### ISSUE TITLE
Petaluma Right (end) Winged Repeat Sign Placement Issue

### ISSUE THREAD

**Issue by Melodykraaft** [steinbergmedia/petaluma#14]
When using the Petaluma font with the MuseScore score writing program the right (end) winged repeat isn't placed at the very end of the last measure in a system. (Left (start) winged repeat sign seems to work fine with this font.
[Petaluma Winged Repeat Issue.pdf](https://github.com/steinbergmedia/petaluma/files/8935615/Petaluma.Winged.Repeat.Issue.pdf)
)

**Comment by dspreadbury** [comment]
My guess is that this is an issue for the MuseScore developers to address, rather than it being a problem with Petaluma. I would suggest you report it to them in their Engraving forum.

**Comment by Jojo-Schmitz** [comment]
Well, it is just Petaluma, as Bravura, Leland, Gonville, Emmentaler or MuseJazz are not having that issue, so I doubt it to be MuseScore's fault, that's why  directed the user here. More likely it is the 'anchor' of that winged barline being wrong somehow, something in the meta data?

**Comment by dspreadbury** [comment]
No, I don't think there's a problem with the bracketTop (U+E003) or bracketBottom (U+E005) glyphs in Petaluma, or the associated metadata. The glyphs work absolutely fine in Dorico with no special treatment, for example.

**Comment by Jojo-Schmitz** [comment]
The corresponding thread on musescore.org is https://musescore.org/en/node/332963 BTW.
I don't think there's any special caseing im MuseScore for Petaluma's repeat barlines or wings, but will double check

**Comment by Jojo-Schmitz** [comment]
There is some special casing for Petaluma, reg. the repeat dots, but that's it, and the same special cases are used for Bravura and Leland too. The code to add the wings does pick on these wings symbols' (`reversedBracketTop` and `reversedBracketBottom`) width though, for all fonts MuseScore supports.

**Comment by Jojo-Schmitz** [comment]
Actually that's not quite true: other fonts have that isssue too, just to a lesser extent. Just Leland and Emmentaler don't, in MuseScore 3.6.2 at least. Petaluma is just the worst in this respect.

**Comment by Jojo-Schmitz** [comment]
MuseScore 4 doesn't seem to have this issue (in a 3.x score you'd need to switch to another font and then back to Petaluma to see it fixed)
So yes, you're probably right, and MuseScore has some bug here, I guess not honouring some engraving defaults, maybe repeatEndingLineThickness`.

**Comment by Jojo-Schmitz** [comment]
I do however wonder whether this is somehow related to #7?
