### ISSUE TITLE
Time signature glyphs too big

### ISSUE THREAD

**Issue by rvilarl** [steinbergmedia/petaluma#15]
The height (h) of the TimeSigN glyphs 0xE080 to 0xE089 are much bigger than those in Bravura (see below). Should they be reduced to 70% of their current size? The other glyphs are a little bit bigger but not that different.

![image](https://user-images.githubusercontent.com/22865285/212471347-117871c9-3194-4228-b8c4-e25bd7895477.png)
![image](https://user-images.githubusercontent.com/22865285/212471360-81d24e21-cf96-434c-ad08-c39c99d9f7a4.png)

**Comment by lpugin** [comment]
@rvilarl out of curiosity: what is the tool you use to generate the inspector images? It looks very useful!

**Comment by dspreadbury** [comment]
It's intentional for Petaluma that the time signature digits are oversized, so that they are larger relative to the staff than conventional time signature digits. It's part of the handwritten style that the font is emulating.

**Comment by rvilarl** [comment]
> @rvilarl out of curiosity: what is the tool you use to generate the inspector images? It looks very useful!

it is a vexflow tool but today it can only be used with the fonts used in vexflow. 

https://github.com/0xfe/vexflow/blob/master/tools/fonts/inspector/glyphs.html

**Comment by rvilarl** [comment]
> It's intentional for Petaluma that the time signature digits are oversized, so that they are larger relative to the staff than conventional time signature digits. It's part of the handwritten style that the font is emulating.

In https://github.com/0xfe/vexflow/ we have to scale them down to avoid that the numbers overlap. They are further scaled down than the other glyphs in Petaluma. Do you use a single scale for all the glyphs in Dorico?

**Comment by dspreadbury** [comment]
Yes, we do. This is how those time signature glyphs look by default in Dorico:

![](https://user-images.githubusercontent.com/1312874/219007204-87c2f214-95b6-42c9-a707-c729bf76c9af.png)

We do have to have a special way of positioning these glyphs, however, since the normal rules for registering them by positioning them on the second and fourth staff lines don't work when they are oversized. We end up positioning them by bottom-aligning the numerator against the middle staff line, and top-aligning the denominator against the middle staff line.

**Comment by lpugin** [comment]
For the record:
* https://github.com/rism-digital/verovio/issues/1184

And the corresponding fix:
* https://github.com/rism-digital/verovio/pull/2386

**Comment by Jojo-Schmitz** [comment]
Just for the record: this is how it looks in MuseScore
![image](https://user-images.githubusercontent.com/1786669/219015554-f33b2092-d7d1-4695-8f93-8e515dcbb70c.png)

**Comment by rvilarl** [comment]
Thanks a lot! 

I still have a question, is there any information related to the required positioning in the json file to make the difference programatically or this must be hardcoded for Petaluma?

And a comment, this does not follow the smufl spec _"Digits for time signatures should be scaled such that each digit is two staff spaces tall, i.e. 0.5 em, and vertically centered on the baseline."_, right? 
(see https://w3c.github.io/smufl/latest/specification/scoring-metrics-glyph-registration.html)

**Comment by dspreadbury** [comment]
Yes, I'm afraid this behaviour is indeed out of spec for SMuFL, which is very naughty! There is at present nothing in the JSON metadata that would help you to make this determination.

**Comment by rvilarl** [comment]
> @rvilarl out of curiosity: what is the tool you use to generate the inspector images? It looks very useful!

@lpugin  I am updating the tool to a font-face generic one, look at this PR https://github.com/vexflow/vexflow/pull/19
