### ISSUE TITLE
Publishing in google fonts

### ISSUE THREAD

**Issue by rvilarl** [steinbergmedia/petaluma#16]
Is it possible to get the font published in Google Fonts? Or is there another preferred CDN?

**Comment by dspreadbury** [comment]
Google Fonts appears to have the requirement that OFL-licensed fonts don't have a reserved font name, which means that Petaluma isn't eligible for inclusion there, as far as I can tell.

**Comment by rvilarl** [comment]
And any other CDN? Or place to locate them?

**Comment by rvilarl** [comment]
And would you have anything against trying to publish them? I can try

**Comment by dspreadbury** [comment]
I certainly have no objection to you trying to publish them.

**Comment by kenmcd** [comment]
Highly unlikely to happen.
GF creates multiple subset fonts using the same name.
The RFN causes issues with this process.
