### ISSUE TITLE
Bottom wing of an end-repeat barline is misplaced

### ISSUE THREAD

**Issue by Jojo-Schmitz** [steinbergmedia/petaluma#7]
See https://musescore.org/en/node/315238, when using  Petaluma and winged repeat barlines, on the end-repeat barline the bottom wing is placed too high:
![image](https://user-images.githubusercontent.com/1786669/103867189-3b632780-50c7-11eb-9660-ec01cd2ba540.png)

I guess (!) it is `reversedBracketBottom` having some bogus settings

        "reversedBracketBottom": {
            "bBoxNE": [
                2.181154700538379, 
                1.68
            ], 
            "bBoxSW": [
                0.0, 
                0.0
            ]
        }, 

I don't think that `bBoxSW` or `bBoxNE` is correct, esp. their y-values?

Works just fine with Bravura (and a couple other SMuFL fonts)

**Comment by dspreadbury** [comment]
The problem was that the registration of the glyph was incorrect (and hence the metadata was also incorrect). Fixed in [version 1.065](https://github.com/steinbergmedia/petaluma/releases/tag/petaluma-1.065).

**Comment by Jojo-Schmitz** [comment]
Thanks! It did miss the release of MuseScore 3.6.1 by some hours, but I'll try to get it into 3.6.2, see https://github.com/musescore/MuseScore/pull/7346
