### ISSUE TITLE
Dynamics are too small in Petaluma Text

### ISSUE THREAD

**Issue by QuaverCrafter** [steinbergmedia/petaluma#8]
Using Leeland, Bravura, Emmentaler, Gonville, or Musejazz, 11 pt. is a good size for dynamics. On this one, 20 pt. seems right. The symbols should be resized to correspond to the other fonts.
![Petaluma size](https://user-images.githubusercontent.com/77705085/105109712-4ed4a200-5a7a-11eb-977a-0d024ef80f68.png)
`

**Comment by dspreadbury** [comment]
Petaluma is sized correctly: the idea for SMuFL music fonts (as opposed to music **text** fonts intended for use inline with regular text fonts) is that you can draw all of the music at a single point size, so a clef, a notehead and a dynamic are all consistent in scale with one another at the same point size. So when you use Petaluma at 20pt, the dynamics will appear the correct size relative to the rest of the music.

Petaluma **Text** on the other hand, which is a music text font, will show you a dynamic that is sized appropriately for 12pt (say) Arial or another text font when it is at 12pt.

For more information about the differences between music fonts and music text fonts, see the [SMuFL specification](https://w3c.github.io/smufl/gitbook/specification/scoring-vs-text-applications.html).

**Comment by Jojo-Schmitz** [comment]
Why then are, in MuseScore, Petaluma dynamics so much smaller than those from Bravura, Emmentaler, Gonville, MuseScore or Leland? Ther are very clearly too small in comparison to all other SMuFL fonts (see above) MuseScore uses (Leland and Petaluma added as of 3.6).

Is that possibly the difference between Petaluma Text and Petaluma Script (which I never understood)?

**Comment by dspreadbury** [comment]
I can only imagine that you're using the wrong font, and MuseScore expects to be using Petaluma Text and not Petaluma for dynamics.

**Comment by Jojo-Schmitz** [comment]
If so: the same would be true for all the other fonts, those don't have the issue though.

See https://musescore.org/en/node/314722 for examples

**Comment by Jojo-Schmitz** [comment]
See https://musescore.org/en/node/314722 for examples

**Comment by dspreadbury** [comment]
Which font is MuseScore using for dynamics? Petaluma, or Petaluma Text?

**Comment by Jojo-Schmitz** [comment]
The same as for Bravura, Leland...  (not really sure whether Text or not, I believe the Text font)

**Comment by dspreadbury** [comment]
It would be helpful to know definitively. I can't look at MuseScore's source code to find out, but you (I assume) can.

**Comment by Jojo-Schmitz** [comment]
WIP. One thing for sure though: Petaluma is not treated differently than any of the other fonts we have in MuseScore, but it does behaves differently.

**Comment by Jojo-Schmitz** [comment]
Petaluma Text

**Comment by dspreadbury** [comment]
Thanks. It's helpful to have a complete and correct bug report. I'll look into what's going on with Petaluma Text.

**Comment by Jojo-Schmitz** [comment]
The Dynamics' looks does change when changing Format > Style > Score > Musical Text Font, in MuseScore, and gets too small when switching to Petaluma Text.

**Comment by dspreadbury** [comment]
This should be much improved in [version 1.065](https://github.com/steinbergmedia/petaluma/releases/tag/petaluma-1.065).

**Comment by Jojo-Schmitz** [comment]
Thanks! It did miss the release of MuseScore 3.6.1 by some hours, but I'll try to get it into 3.6.2, see https://github.com/musescore/MuseScore/pull/7346
